// Generated by purs bundle 0.14.7
var PS = {};
(function(exports) {
  /* global exports */
  "use strict";

  exports.unsafeForeignProcedure = function(args) {
      return function (stmt) {
          return Function(wrap(args.slice()))();
          function wrap() {
              return !args.length ? stmt : 'return function (' + args.shift() + ') { ' + wrap() + ' };';
          }
      };
  };
})(PS["Data.Foreign.EasyFFI"] = PS["Data.Foreign.EasyFFI"] || {});
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Data.Foreign.EasyFFI"] = $PS["Data.Foreign.EasyFFI"] || {};
  var exports = $PS["Data.Foreign.EasyFFI"];
  var $foreign = $PS["Data.Foreign.EasyFFI"];
  var unsafeForeignFunction = function (args) {
      return function (expr) {
          return $foreign.unsafeForeignProcedure(args)("return " + (expr + ";"));
      };
  };
  exports["unsafeForeignFunction"] = unsafeForeignFunction;
  exports["unsafeForeignProcedure"] = $foreign.unsafeForeignProcedure;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Util"] = $PS["Graphics.Three.Util"] || {};
  var exports = $PS["Graphics.Three.Util"];
  var Data_Foreign_EasyFFI = $PS["Data.Foreign.EasyFFI"];                
  var fpi = Data_Foreign_EasyFFI.unsafeForeignProcedure;
  var ffi = Data_Foreign_EasyFFI.unsafeForeignFunction;
  exports["ffi"] = ffi;
  exports["fpi"] = fpi;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Camera"] = $PS["Graphics.Three.Camera"] || {};
  var exports = $PS["Graphics.Three.Camera"];
  var Graphics_Three_Util = $PS["Graphics.Three.Util"];
  var createPerspective = Graphics_Three_Util.ffi([ "fov", "aspect", "near", "far", "" ])("new THREE.PerspectiveCamera(fov, aspect, near, far)");
  exports["createPerspective"] = createPerspective;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Geometry"] = $PS["Graphics.Three.Geometry"] || {};
  var exports = $PS["Graphics.Three.Geometry"];
  var Graphics_Three_Util = $PS["Graphics.Three.Util"];                                                                                                                        
  var createBox = Graphics_Three_Util.ffi([ "width", "height", "depth", "" ])("new THREE.BoxGeometry(width, height, depth)");
  exports["createBox"] = createBox;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Material"] = $PS["Graphics.Three.Material"] || {};
  var exports = $PS["Graphics.Three.Material"];
  var Graphics_Three_Util = $PS["Graphics.Three.Util"];                                          
  var createMeshBasic = Graphics_Three_Util.ffi([ "param", "" ])("new THREE.MeshBasicMaterial(param)");
  exports["createMeshBasic"] = createMeshBasic;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Object3D"] = $PS["Graphics.Three.Object3D"] || {};
  var exports = $PS["Graphics.Three.Object3D"];
  var Graphics_Three_Util = $PS["Graphics.Three.Util"];
  var setRotationEuler = function () {
      return Graphics_Three_Util.fpi([ "object", "x", "y", "z", "" ])("object.rotation.set(x, y, z)");
  };
  var setPosition = function () {
      return Graphics_Three_Util.fpi([ "object", "x", "y", "z", "" ])("object.position.set(x, y, z)");
  };
  var createMesh = function () {
      return Graphics_Three_Util.ffi([ "geometry", "material", "" ])("new THREE.Mesh(geometry, material)");
  };
  exports["createMesh"] = createMesh;
  exports["setPosition"] = setPosition;
  exports["setRotationEuler"] = setRotationEuler;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Renderer"] = $PS["Graphics.Three.Renderer"] || {};
  var exports = $PS["Graphics.Three.Renderer"];
  var Graphics_Three_Util = $PS["Graphics.Three.Util"];                
  var setSize = Graphics_Three_Util.ffi([ "renderer", "width", "height", "" ])("renderer.setSize(width, height)");
  var render = function () {
      return Graphics_Three_Util.fpi([ "renderer", "scene", "camera", "" ])("renderer.render(scene, camera)");
  };                                                                                  
  var createWebGL = Graphics_Three_Util.ffi([ "params", "" ])("new THREE.WebGLRenderer(params)");
  var appendToDomByID = Graphics_Three_Util.fpi([ "renderer", "idStr", "" ])("document.getElementById(idStr).appendChild(renderer.domElement)");
  exports["createWebGL"] = createWebGL;
  exports["setSize"] = setSize;
  exports["render"] = render;
  exports["appendToDomByID"] = appendToDomByID;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Graphics.Three.Scene"] = $PS["Graphics.Three.Scene"] || {};
  var exports = $PS["Graphics.Three.Scene"];
  var Graphics_Three_Util = $PS["Graphics.Three.Util"];                
  var create = Graphics_Three_Util.ffi([ "" ])("new THREE.Scene()");
  var addObject = function () {
      return Graphics_Three_Util.fpi([ "scene", "a", "" ])("scene.add(a)");
  };
  exports["create"] = create;
  exports["addObject"] = addObject;
})(PS);
(function($PS) {
  "use strict";
  $PS["ThreeJS"] = $PS["ThreeJS"] || {};
  var exports = $PS["ThreeJS"];
  var Data_Foreign_EasyFFI = $PS["Data.Foreign.EasyFFI"];
  var wrapTmirroredRepeat = function () {
      return Data_Foreign_EasyFFI.unsafeForeignFunction([ "texture", "" ])("texture.wrapT = THREE.MirroredRepeatWrapping;");
  };
  var wrapSmirroredRepeat = function () {
      return Data_Foreign_EasyFFI.unsafeForeignFunction([ "texture", "" ])("texture.wrapS = THREE.MirroredRepeatWrapping;");
  };
  var unsafePrint = Data_Foreign_EasyFFI.unsafeForeignProcedure([ "a", "" ])("console.log(a)");

  // Importing
  var textureLoader = Data_Foreign_EasyFFI.unsafeForeignFunction([ "param", "" ])("new THREE.TextureLoader().load(param)");

  // GENERAL
  var requestAnimationFrame = Data_Foreign_EasyFFI.unsafeForeignProcedure([ "callback", "" ])("window.requestAnimationFrame(callback)");

  //
  var repeatSet = function () {
      return Data_Foreign_EasyFFI.unsafeForeignProcedure([ "texture", "x", "y", "" ])("texture.repeat.set(x,y);");
  };
  var createVideoById = Data_Foreign_EasyFFI.unsafeForeignFunction([ "id", "" ])("document.createElement(id)");
  exports["textureLoader"] = textureLoader;
  exports["createVideoById"] = createVideoById;
  exports["wrapSmirroredRepeat"] = wrapSmirroredRepeat;
  exports["wrapTmirroredRepeat"] = wrapTmirroredRepeat;
  exports["repeatSet"] = repeatSet;
  exports["requestAnimationFrame"] = requestAnimationFrame;
  exports["unsafePrint"] = unsafePrint;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.7
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Graphics_Three_Camera = $PS["Graphics.Three.Camera"];
  var Graphics_Three_Geometry = $PS["Graphics.Three.Geometry"];
  var Graphics_Three_Material = $PS["Graphics.Three.Material"];
  var Graphics_Three_Object3D = $PS["Graphics.Three.Object3D"];
  var Graphics_Three_Renderer = $PS["Graphics.Three.Renderer"];
  var Graphics_Three_Scene = $PS["Graphics.Three.Scene"];
  var ThreeJS = $PS["ThreeJS"];                
  var animate = function (re) {
      return function __do() {
          Graphics_Three_Renderer.render()(re.renderer)(re.scene)(re.camera)();
          return ThreeJS.requestAnimationFrame(animate(re))();
      };
  };
  var main = function __do() {
      var scene = Graphics_Three_Scene.create();
      var camera = Graphics_Three_Camera.createPerspective(75.0)(16.0 / 9.0)(0.1)(100.0)();
      var renderer = Graphics_Three_Renderer.createWebGL({
          antialias: true
      })();
      Graphics_Three_Renderer.setSize(renderer)(1250.0)(720.0)();
      Graphics_Three_Renderer.appendToDomByID(renderer)("canvas")();
      Graphics_Three_Object3D.setPosition()(camera)(0.0)(0.0)(5.0)();
      var video = ThreeJS.createVideoById("video")();
      ThreeJS.unsafePrint(video)();
      var texture = ThreeJS.textureLoader("src/textures/cellos.jpg")();
      ThreeJS.wrapSmirroredRepeat()(texture)();
      ThreeJS.wrapTmirroredRepeat()(texture)();
      ThreeJS.repeatSet()(texture)(2.0)(2.0)();
      ThreeJS.unsafePrint(texture)();
      var material = Graphics_Three_Material.createMeshBasic({
          map: texture
      })();
      ThreeJS.unsafePrint(material)();
      var geometry = Graphics_Three_Geometry.createBox(2.0)(2.0)(2.0)();
      var mesh = Graphics_Three_Object3D.createMesh()(geometry)(material)();
      Graphics_Three_Scene.addObject()(scene)(mesh)();
      Graphics_Three_Object3D.setRotationEuler()(mesh)(1.5)(0.5)(0.5)();
      var re = {
          scene: scene,
          camera: camera,
          renderer: renderer
      };
      ThreeJS.requestAnimationFrame(animate(re))();
      return re;
  };
  exports["main"] = main;
  exports["animate"] = animate;
})(PS);
PS["Main"].main();